name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 每日 00:00 UTC 运行（北京时间 08:00）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Frank-Loong
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      - name: Commit snake files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name  "github-actions[bot]"
          git add output/github-snake*.svg
          git commit -m "chore: generate snake contribution graph" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 